[package]
name = "h3arrow"
version = "0.1.0"
edition = "2021"
authors = ["Nico Mandery <nico@nmandery.net>"]
license = "MIT"
keywords = ["geo", "spatial", "h3"]
readme = "README.md"
homepage = "https://github.com/nmandery/h3arrow"
repository = "https://github.com/nmandery/h3arrow"

[package.metadata.docs.rs]
all-features = true

[features]
geoarrow = ["dep:geoarrow", "dep:geozero"]
rayon = ["dep:rayon"]

[dependencies]
ahash = "0.8"
arrow2 = { version = "0.17", features = [] }
geo = "0.25"
geoarrow = { git = "https://github.com/nmandery/geoarrow", rev = "1b7fb57847ccd2042c1b0e2f995fa3c446ebaa6f", optional = true }
geo-types = "0.7"
geozero = { version = "0.9", default-features = false, features = ["with-geo", "with-wkb"], optional = true }
h3o = { version = "0.3", features = ["geo"] }
nom = "7"
rayon = { version = "1", optional = true }
thiserror = "1"
